configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/woodside-labs%2Ffiatwebservices-08af94ade35eb26717204bf936aa08c06b93e0f5e4e749608656fcc0a6289d15.yml
