configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/woodside-labs%2Ffiatwebservices-52f42fab79c6ef53e739f79e647881daa6be87818a668d7bd948a5186ca497ff.yml
