configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/woodside-labs%2Ffiatwebservices-a8bfd8817bbce540198c6ddbab84c910b50b4c05efdc26519eb56536da9b7347.yml
